version: '3'

services:
  db:
    image: postgres
    volumes:
        - db-data:/var/lib/postgresql/data
  api:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
        - .env
    command: gunicorn bdtapi.wsgi -b 0.0.0.0:8000 --workers=2 --threads=4 --worker-class=gthread --reload

volumes:
    db-data:
