# Generated by Django 2.2.2 on 2019-06-17 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timebank', '0002_auto_20190617_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timebank.Account'),
        ),
    ]
