# Generated by Django 2.2.2 on 2019-06-17 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timebank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(verbose_name='Saldo'),
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.IntegerField(choices=[(0, 'Entrada'), (1, 'Saída')], verbose_name='Tipo de transação')),
                ('delta', models.IntegerField(help_text='Delta do saldo')),
                ('reference', models.TextField()),
                ('debug_balace', models.IntegerField(help_text='Saldo depois da transação')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
    ]
