# Generated by Django 2.2.3 on 2019-07-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='delta',
            field=models.DecimalField(decimal_places=1, help_text='Valor da transação', max_digits=5, verbose_name='Saldo'),
        ),
    ]
