# Generated by Django 2.2.3 on 2019-07-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebank', '0002_auto_20190721_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttransaction',
            name='debug_balace',
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='delta',
            field=models.DecimalField(decimal_places=1, help_text='Valor da transação', max_digits=5, verbose_name='Valor da transação'),
        ),
    ]
