# Generated by Django 2.2.3 on 2019-08-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebank', '0005_auto_20190803_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='balance_after_transaction',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Saldo depois da transação', max_digits=5, verbose_name='Saldo depois da transação'),
            preserve_default=False,
        ),
    ]
