# Generated by Django 2.2.14 on 2020-07-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timebank', '0007_auto_20190808_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttransaction',
            name='reference',
        ),
    ]
