# Generated by Django 2.2.3 on 2019-07-27 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('order_price', models.DecimalField(decimal_places=1, help_text='Valor da troca', max_digits=5, verbose_name='Valor da troca')),
                ('status', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Efetuado')], verbose_name='Status do pedido')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('grantor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grantor', to=settings.AUTH_USER_MODEL, verbose_name='Concedente')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requester', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
