# Generated by Django 2.2.3 on 2019-08-08 03:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190803_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador Público'),
        ),
    ]
